version: "3.3"

services:
  redis:
    image: jtl-tkgiharbor.hq.bni.co.id/soadev/redis
    ports:
      - 6379:6379
    networks:
      - network-service-ham

  oracle:
    image: jtl-tkgiharbor.hq.bni.co.id/soadev/openjdk11-oracle
    build:
      context: .
    ports:
      - 1521:1521
    networks:
      - network-service-ham

  network-service:
    image: jtl-tkgiharbor.hq.bni.co.id/soadev/network-service
    ports:
      - "9101:8080"
    networks:
      - network-service-ham
      
networks:
  network-service-ham:
    - name: network-service-ham
      driver: overlay
